services:
  db:
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
  app:
    env_file:
      - .env
    environment:
      - DB_MONGO_USER=$MONGO_USERNAME
      - DB_MONGO_PASSWORD=$MONGO_PASSWORD
      - DB_MONGO_HOST=db
      - DB_MONGO_PORT=27017
      - DB_MONGO_MAX_POOL_SIZE=20
      - DB_MONGO_DB=$MONGO_DB
      - NODE_ENV=production
      - DB_MONGO_VERSION=
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile

    develop:
      watch:
        - action: rebuild
          path: ./frontend
          ignore:
            - node_modules/
            - .svele-kit/
        - action: rebuild
          path: ./backend
          ignore:
          - build/
          - .idea/
          - .gradle/
    ports:
      - 8080:8080
volumes:
  dbdata:
